config/routes.rb
Rails.application.routes.draw do
  get 'pixabay/search'
  get 'pexels/search'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pexels_controller.rb
class PexelsController < ApplicationController
  def search
    @query = params.fetch(:query, "background")

    @filter_tags = params.fetch(:filter_tags, %w[male female girl boy person hand couple hair people arms adult child man woman feet group].join(",")).split(",")
    @boost_tags = params.fetch(:boost_tags, %w[background wallpaper].join(",")).split(",")

    @pexels = Pexels.new
    @photos, @total_results, @page  = @pexels.search(@query, @filter_tags, @boost_tags)
  end
end

app/controllers/pixabay_controller.rb
class PixabayController < ApplicationController
  def search
    @query = params.fetch(:query, "beach")
    @filter_tags = params.fetch(:filter_tags, %w[male female girl boy person hand couple hair people arms adult child man woman feet group].join(",")).split(",")

    @pixabay = Pixabay.new
    @photos, @total_results = @pixabay.search(@query, @filter_tags)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PexelsExplorer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container mx-auto">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pexels/search.html.erb
<%= form_with url: pexels_search_path, method: :get, local: true, class: "my-6" do %>
  <div class="flex items-center">
    <label class="block w-full mr-2">
      <span class="text-gray-700">Query</span>
      <%= text_field_tag :query, @query, class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-green-300 focus:ring focus:ring-green-200 focus:ring-opacity-50" %>
    </label>
    <label class="block w-full mr-2">
      <span class="text-gray-700"> Bad Tags</span>
      <%= text_field_tag :filter_tags, @filter_tags.join(","), class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-green-300 focus:ring focus:ring-green-200 focus:ring-opacity-50" %>
    </label>
    <label class="block w-full mr-2">
      <span class="text-gray-700">Good Tags</span>
      <%= text_field_tag :boost_tags, @boost_tags.join(","), class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-green-300 focus:ring focus:ring-green-200 focus:ring-opacity-50" %>
    </label>
    <%= submit_tag "Search", class: "self-end bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded cursor-pointer ml-1" %>
  </div>
<% end %>

<ul class="mb-6">
  <li>Total API Results: <strong><%= @total_results %></strong></li>
</ul>

<% if @photos.empty? %>
  <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
    <strong class="font-bold">Oh no!</strong>
    <span class="block sm:inline">No suitable photos found</span>
  </div>
<% end %>

<div class="grid grid-cols-4 gap-2">
  <% @photos.each do |photo| %>
    <div class="flex flex-col">
      <%= image_tag photo.src.medium %>
      <p class="p-2 text-xs text-gray-500 font-mono">Result rating: <%= photo.rating %></p>
      <p class="p-2 text-xs text-gray-500 font-mono">
        <%= photo.tags.join(", ") %>
      </p>
    </div>
  <% end %>
</div>

app/views/pixabay/search.html.erb
<%= form_with url: pixabay_search_path, method: :get, local: true, class: "my-6" do %>
  <div class="flex items-center">
    <label class="block w-full mr-2">
      <span class="text-gray-700">Query</span>
      <%= text_field_tag :query, @query, class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-green-300 focus:ring focus:ring-green-200 focus:ring-opacity-50" %>
    </label>
    <!--
    <label class="block w-full mr-2">
      <span class="text-gray-700"> Bad Tags</span>
      <%= text_field_tag :filter_tags, @filter_tags.join(","), class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-green-300 focus:ring focus:ring-green-200 focus:ring-opacity-50" %>
    </label>
    -->
    <%= submit_tag "Search", class: "self-end bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded cursor-pointer ml-1" %>
  </div>
<% end %>

<ul class="mb-6">
  <li>Total API Results: <strong><%= @total_results %></strong></li>
</ul>

<% if @photos.empty? %>
  <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
    <strong class="font-bold">Oh no!</strong>
    <span class="block sm:inline">No suitable photos found</span>
  </div>
<% end %>

<div class="grid grid-cols-4 gap-2">
  <% @photos.each do |photo| %>
    <div class="flex flex-col">
      <%= image_tag photo.webformatURL %>
      <p class="p-2 text-xs text-gray-500 font-mono">
        <%= photo.tags %>
      </p>
    </div>
  <% end %>
</div>